services:
  app:
    build: .
    volumes:
      - .:/var/www
    environment:
      - DB_HOST=db
      - DB_NAME=yii2
      - DB_USER=root
      - DB_PASSWORD=root
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - .:/var/www
    depends_on:
      - app

  db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yii2
    volumes:
      - db_data:/var/lib/mysql

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 0
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8001:80"
    depends_on:
      - db

volumes:
  db_data: